// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/fragilebox/protocol/BoxProtocol.proto

package io.fragilebox.protocol;

public final class BoxProtocol {
  private BoxProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BenchmarkResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 messageTime = 1;
    /**
     * <code>optional int64 messageTime = 1;</code>
     *
     * <pre>
     * Time to process one message, in microseconds
     * </pre>
     */
    boolean hasMessageTime();
    /**
     * <code>optional int64 messageTime = 1;</code>
     *
     * <pre>
     * Time to process one message, in microseconds
     * </pre>
     */
    long getMessageTime();

    // optional int32 processedMessages = 2;
    /**
     * <code>optional int32 processedMessages = 2;</code>
     *
     * <pre>
     * Number of processed messages
     * </pre>
     */
    boolean hasProcessedMessages();
    /**
     * <code>optional int32 processedMessages = 2;</code>
     *
     * <pre>
     * Number of processed messages
     * </pre>
     */
    int getProcessedMessages();
  }
  /**
   * Protobuf type {@code io.fragilebox.protocol.BenchmarkResult}
   *
   * <pre>
   ****
   * Messages to measure overhead of the FragileBox Protocol.
   ****
   * </pre>
   */
  public static final class BenchmarkResult extends
      com.google.protobuf.GeneratedMessage
      implements BenchmarkResultOrBuilder {
    // Use BenchmarkResult.newBuilder() to construct.
    private BenchmarkResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BenchmarkResult(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BenchmarkResult defaultInstance;
    public static BenchmarkResult getDefaultInstance() {
      return defaultInstance;
    }

    public BenchmarkResult getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BenchmarkResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              messageTime_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              processedMessages_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.fragilebox.protocol.BoxProtocol.internal_static_io_fragilebox_protocol_BenchmarkResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.fragilebox.protocol.BoxProtocol.internal_static_io_fragilebox_protocol_BenchmarkResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.fragilebox.protocol.BoxProtocol.BenchmarkResult.class, io.fragilebox.protocol.BoxProtocol.BenchmarkResult.Builder.class);
    }

    public static com.google.protobuf.Parser<BenchmarkResult> PARSER =
        new com.google.protobuf.AbstractParser<BenchmarkResult>() {
      public BenchmarkResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BenchmarkResult(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BenchmarkResult> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 messageTime = 1;
    public static final int MESSAGETIME_FIELD_NUMBER = 1;
    private long messageTime_;
    /**
     * <code>optional int64 messageTime = 1;</code>
     *
     * <pre>
     * Time to process one message, in microseconds
     * </pre>
     */
    public boolean hasMessageTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 messageTime = 1;</code>
     *
     * <pre>
     * Time to process one message, in microseconds
     * </pre>
     */
    public long getMessageTime() {
      return messageTime_;
    }

    // optional int32 processedMessages = 2;
    public static final int PROCESSEDMESSAGES_FIELD_NUMBER = 2;
    private int processedMessages_;
    /**
     * <code>optional int32 processedMessages = 2;</code>
     *
     * <pre>
     * Number of processed messages
     * </pre>
     */
    public boolean hasProcessedMessages() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 processedMessages = 2;</code>
     *
     * <pre>
     * Number of processed messages
     * </pre>
     */
    public int getProcessedMessages() {
      return processedMessages_;
    }

    private void initFields() {
      messageTime_ = 0L;
      processedMessages_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, messageTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, processedMessages_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, messageTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, processedMessages_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.fragilebox.protocol.BoxProtocol.BenchmarkResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.fragilebox.protocol.BoxProtocol.BenchmarkResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.fragilebox.protocol.BoxProtocol.BenchmarkResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.fragilebox.protocol.BoxProtocol.BenchmarkResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.fragilebox.protocol.BoxProtocol.BenchmarkResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.fragilebox.protocol.BoxProtocol.BenchmarkResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.fragilebox.protocol.BoxProtocol.BenchmarkResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.fragilebox.protocol.BoxProtocol.BenchmarkResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.fragilebox.protocol.BoxProtocol.BenchmarkResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.fragilebox.protocol.BoxProtocol.BenchmarkResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.fragilebox.protocol.BoxProtocol.BenchmarkResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.fragilebox.protocol.BenchmarkResult}
     *
     * <pre>
     ****
     * Messages to measure overhead of the FragileBox Protocol.
     ****
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements io.fragilebox.protocol.BoxProtocol.BenchmarkResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.fragilebox.protocol.BoxProtocol.internal_static_io_fragilebox_protocol_BenchmarkResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.fragilebox.protocol.BoxProtocol.internal_static_io_fragilebox_protocol_BenchmarkResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.fragilebox.protocol.BoxProtocol.BenchmarkResult.class, io.fragilebox.protocol.BoxProtocol.BenchmarkResult.Builder.class);
      }

      // Construct using io.fragilebox.protocol.BoxProtocol.BenchmarkResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messageTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        processedMessages_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.fragilebox.protocol.BoxProtocol.internal_static_io_fragilebox_protocol_BenchmarkResult_descriptor;
      }

      public io.fragilebox.protocol.BoxProtocol.BenchmarkResult getDefaultInstanceForType() {
        return io.fragilebox.protocol.BoxProtocol.BenchmarkResult.getDefaultInstance();
      }

      public io.fragilebox.protocol.BoxProtocol.BenchmarkResult build() {
        io.fragilebox.protocol.BoxProtocol.BenchmarkResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.fragilebox.protocol.BoxProtocol.BenchmarkResult buildPartial() {
        io.fragilebox.protocol.BoxProtocol.BenchmarkResult result = new io.fragilebox.protocol.BoxProtocol.BenchmarkResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageTime_ = messageTime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.processedMessages_ = processedMessages_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.fragilebox.protocol.BoxProtocol.BenchmarkResult) {
          return mergeFrom((io.fragilebox.protocol.BoxProtocol.BenchmarkResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.fragilebox.protocol.BoxProtocol.BenchmarkResult other) {
        if (other == io.fragilebox.protocol.BoxProtocol.BenchmarkResult.getDefaultInstance()) return this;
        if (other.hasMessageTime()) {
          setMessageTime(other.getMessageTime());
        }
        if (other.hasProcessedMessages()) {
          setProcessedMessages(other.getProcessedMessages());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.fragilebox.protocol.BoxProtocol.BenchmarkResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.fragilebox.protocol.BoxProtocol.BenchmarkResult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 messageTime = 1;
      private long messageTime_ ;
      /**
       * <code>optional int64 messageTime = 1;</code>
       *
       * <pre>
       * Time to process one message, in microseconds
       * </pre>
       */
      public boolean hasMessageTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 messageTime = 1;</code>
       *
       * <pre>
       * Time to process one message, in microseconds
       * </pre>
       */
      public long getMessageTime() {
        return messageTime_;
      }
      /**
       * <code>optional int64 messageTime = 1;</code>
       *
       * <pre>
       * Time to process one message, in microseconds
       * </pre>
       */
      public Builder setMessageTime(long value) {
        bitField0_ |= 0x00000001;
        messageTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 messageTime = 1;</code>
       *
       * <pre>
       * Time to process one message, in microseconds
       * </pre>
       */
      public Builder clearMessageTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageTime_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 processedMessages = 2;
      private int processedMessages_ ;
      /**
       * <code>optional int32 processedMessages = 2;</code>
       *
       * <pre>
       * Number of processed messages
       * </pre>
       */
      public boolean hasProcessedMessages() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 processedMessages = 2;</code>
       *
       * <pre>
       * Number of processed messages
       * </pre>
       */
      public int getProcessedMessages() {
        return processedMessages_;
      }
      /**
       * <code>optional int32 processedMessages = 2;</code>
       *
       * <pre>
       * Number of processed messages
       * </pre>
       */
      public Builder setProcessedMessages(int value) {
        bitField0_ |= 0x00000002;
        processedMessages_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 processedMessages = 2;</code>
       *
       * <pre>
       * Number of processed messages
       * </pre>
       */
      public Builder clearProcessedMessages() {
        bitField0_ = (bitField0_ & ~0x00000002);
        processedMessages_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:io.fragilebox.protocol.BenchmarkResult)
    }

    static {
      defaultInstance = new BenchmarkResult(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:io.fragilebox.protocol.BenchmarkResult)
  }

  public interface BenchmarkOptionsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 benchmarkSize = 3;
    /**
     * <code>optional int32 benchmarkSize = 3;</code>
     *
     * <pre>
     * Number of request messages to send within benchmark
     * </pre>
     */
    boolean hasBenchmarkSize();
    /**
     * <code>optional int32 benchmarkSize = 3;</code>
     *
     * <pre>
     * Number of request messages to send within benchmark
     * </pre>
     */
    int getBenchmarkSize();

    // optional int32 payloadSize = 4;
    /**
     * <code>optional int32 payloadSize = 4;</code>
     *
     * <pre>
     * Size of payload (should be divisible by 4) in one message
     * </pre>
     */
    boolean hasPayloadSize();
    /**
     * <code>optional int32 payloadSize = 4;</code>
     *
     * <pre>
     * Size of payload (should be divisible by 4) in one message
     * </pre>
     */
    int getPayloadSize();
  }
  /**
   * Protobuf type {@code io.fragilebox.protocol.BenchmarkOptions}
   */
  public static final class BenchmarkOptions extends
      com.google.protobuf.GeneratedMessage
      implements BenchmarkOptionsOrBuilder {
    // Use BenchmarkOptions.newBuilder() to construct.
    private BenchmarkOptions(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BenchmarkOptions(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BenchmarkOptions defaultInstance;
    public static BenchmarkOptions getDefaultInstance() {
      return defaultInstance;
    }

    public BenchmarkOptions getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BenchmarkOptions(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000001;
              benchmarkSize_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000002;
              payloadSize_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.fragilebox.protocol.BoxProtocol.internal_static_io_fragilebox_protocol_BenchmarkOptions_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.fragilebox.protocol.BoxProtocol.internal_static_io_fragilebox_protocol_BenchmarkOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.fragilebox.protocol.BoxProtocol.BenchmarkOptions.class, io.fragilebox.protocol.BoxProtocol.BenchmarkOptions.Builder.class);
    }

    public static com.google.protobuf.Parser<BenchmarkOptions> PARSER =
        new com.google.protobuf.AbstractParser<BenchmarkOptions>() {
      public BenchmarkOptions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BenchmarkOptions(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BenchmarkOptions> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 benchmarkSize = 3;
    public static final int BENCHMARKSIZE_FIELD_NUMBER = 3;
    private int benchmarkSize_;
    /**
     * <code>optional int32 benchmarkSize = 3;</code>
     *
     * <pre>
     * Number of request messages to send within benchmark
     * </pre>
     */
    public boolean hasBenchmarkSize() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 benchmarkSize = 3;</code>
     *
     * <pre>
     * Number of request messages to send within benchmark
     * </pre>
     */
    public int getBenchmarkSize() {
      return benchmarkSize_;
    }

    // optional int32 payloadSize = 4;
    public static final int PAYLOADSIZE_FIELD_NUMBER = 4;
    private int payloadSize_;
    /**
     * <code>optional int32 payloadSize = 4;</code>
     *
     * <pre>
     * Size of payload (should be divisible by 4) in one message
     * </pre>
     */
    public boolean hasPayloadSize() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 payloadSize = 4;</code>
     *
     * <pre>
     * Size of payload (should be divisible by 4) in one message
     * </pre>
     */
    public int getPayloadSize() {
      return payloadSize_;
    }

    private void initFields() {
      benchmarkSize_ = 0;
      payloadSize_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(3, benchmarkSize_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(4, payloadSize_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, benchmarkSize_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, payloadSize_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.fragilebox.protocol.BoxProtocol.BenchmarkOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.fragilebox.protocol.BoxProtocol.BenchmarkOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.fragilebox.protocol.BoxProtocol.BenchmarkOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.fragilebox.protocol.BoxProtocol.BenchmarkOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.fragilebox.protocol.BoxProtocol.BenchmarkOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.fragilebox.protocol.BoxProtocol.BenchmarkOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.fragilebox.protocol.BoxProtocol.BenchmarkOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.fragilebox.protocol.BoxProtocol.BenchmarkOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.fragilebox.protocol.BoxProtocol.BenchmarkOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.fragilebox.protocol.BoxProtocol.BenchmarkOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.fragilebox.protocol.BoxProtocol.BenchmarkOptions prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.fragilebox.protocol.BenchmarkOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements io.fragilebox.protocol.BoxProtocol.BenchmarkOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.fragilebox.protocol.BoxProtocol.internal_static_io_fragilebox_protocol_BenchmarkOptions_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.fragilebox.protocol.BoxProtocol.internal_static_io_fragilebox_protocol_BenchmarkOptions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.fragilebox.protocol.BoxProtocol.BenchmarkOptions.class, io.fragilebox.protocol.BoxProtocol.BenchmarkOptions.Builder.class);
      }

      // Construct using io.fragilebox.protocol.BoxProtocol.BenchmarkOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        benchmarkSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        payloadSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.fragilebox.protocol.BoxProtocol.internal_static_io_fragilebox_protocol_BenchmarkOptions_descriptor;
      }

      public io.fragilebox.protocol.BoxProtocol.BenchmarkOptions getDefaultInstanceForType() {
        return io.fragilebox.protocol.BoxProtocol.BenchmarkOptions.getDefaultInstance();
      }

      public io.fragilebox.protocol.BoxProtocol.BenchmarkOptions build() {
        io.fragilebox.protocol.BoxProtocol.BenchmarkOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.fragilebox.protocol.BoxProtocol.BenchmarkOptions buildPartial() {
        io.fragilebox.protocol.BoxProtocol.BenchmarkOptions result = new io.fragilebox.protocol.BoxProtocol.BenchmarkOptions(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.benchmarkSize_ = benchmarkSize_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.payloadSize_ = payloadSize_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.fragilebox.protocol.BoxProtocol.BenchmarkOptions) {
          return mergeFrom((io.fragilebox.protocol.BoxProtocol.BenchmarkOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.fragilebox.protocol.BoxProtocol.BenchmarkOptions other) {
        if (other == io.fragilebox.protocol.BoxProtocol.BenchmarkOptions.getDefaultInstance()) return this;
        if (other.hasBenchmarkSize()) {
          setBenchmarkSize(other.getBenchmarkSize());
        }
        if (other.hasPayloadSize()) {
          setPayloadSize(other.getPayloadSize());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.fragilebox.protocol.BoxProtocol.BenchmarkOptions parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.fragilebox.protocol.BoxProtocol.BenchmarkOptions) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 benchmarkSize = 3;
      private int benchmarkSize_ ;
      /**
       * <code>optional int32 benchmarkSize = 3;</code>
       *
       * <pre>
       * Number of request messages to send within benchmark
       * </pre>
       */
      public boolean hasBenchmarkSize() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 benchmarkSize = 3;</code>
       *
       * <pre>
       * Number of request messages to send within benchmark
       * </pre>
       */
      public int getBenchmarkSize() {
        return benchmarkSize_;
      }
      /**
       * <code>optional int32 benchmarkSize = 3;</code>
       *
       * <pre>
       * Number of request messages to send within benchmark
       * </pre>
       */
      public Builder setBenchmarkSize(int value) {
        bitField0_ |= 0x00000001;
        benchmarkSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 benchmarkSize = 3;</code>
       *
       * <pre>
       * Number of request messages to send within benchmark
       * </pre>
       */
      public Builder clearBenchmarkSize() {
        bitField0_ = (bitField0_ & ~0x00000001);
        benchmarkSize_ = 0;
        onChanged();
        return this;
      }

      // optional int32 payloadSize = 4;
      private int payloadSize_ ;
      /**
       * <code>optional int32 payloadSize = 4;</code>
       *
       * <pre>
       * Size of payload (should be divisible by 4) in one message
       * </pre>
       */
      public boolean hasPayloadSize() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 payloadSize = 4;</code>
       *
       * <pre>
       * Size of payload (should be divisible by 4) in one message
       * </pre>
       */
      public int getPayloadSize() {
        return payloadSize_;
      }
      /**
       * <code>optional int32 payloadSize = 4;</code>
       *
       * <pre>
       * Size of payload (should be divisible by 4) in one message
       * </pre>
       */
      public Builder setPayloadSize(int value) {
        bitField0_ |= 0x00000002;
        payloadSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 payloadSize = 4;</code>
       *
       * <pre>
       * Size of payload (should be divisible by 4) in one message
       * </pre>
       */
      public Builder clearPayloadSize() {
        bitField0_ = (bitField0_ & ~0x00000002);
        payloadSize_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:io.fragilebox.protocol.BenchmarkOptions)
    }

    static {
      defaultInstance = new BenchmarkOptions(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:io.fragilebox.protocol.BenchmarkOptions)
  }

  public interface BenchmarkMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .io.fragilebox.protocol.BenchmarkMessage.Type type = 1;
    /**
     * <code>required .io.fragilebox.protocol.BenchmarkMessage.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .io.fragilebox.protocol.BenchmarkMessage.Type type = 1;</code>
     */
    io.fragilebox.protocol.BoxProtocol.BenchmarkMessage.Type getType();

    // required int32 id = 2;
    /**
     * <code>required int32 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 2;</code>
     */
    int getId();

    // repeated sfixed32 payload = 3;
    /**
     * <code>repeated sfixed32 payload = 3;</code>
     */
    java.util.List<java.lang.Integer> getPayloadList();
    /**
     * <code>repeated sfixed32 payload = 3;</code>
     */
    int getPayloadCount();
    /**
     * <code>repeated sfixed32 payload = 3;</code>
     */
    int getPayload(int index);

    // optional .io.fragilebox.protocol.BenchmarkOptions options = 4;
    /**
     * <code>optional .io.fragilebox.protocol.BenchmarkOptions options = 4;</code>
     */
    boolean hasOptions();
    /**
     * <code>optional .io.fragilebox.protocol.BenchmarkOptions options = 4;</code>
     */
    io.fragilebox.protocol.BoxProtocol.BenchmarkOptions getOptions();
    /**
     * <code>optional .io.fragilebox.protocol.BenchmarkOptions options = 4;</code>
     */
    io.fragilebox.protocol.BoxProtocol.BenchmarkOptionsOrBuilder getOptionsOrBuilder();

    // optional .io.fragilebox.protocol.BenchmarkResult result = 5;
    /**
     * <code>optional .io.fragilebox.protocol.BenchmarkResult result = 5;</code>
     */
    boolean hasResult();
    /**
     * <code>optional .io.fragilebox.protocol.BenchmarkResult result = 5;</code>
     */
    io.fragilebox.protocol.BoxProtocol.BenchmarkResult getResult();
    /**
     * <code>optional .io.fragilebox.protocol.BenchmarkResult result = 5;</code>
     */
    io.fragilebox.protocol.BoxProtocol.BenchmarkResultOrBuilder getResultOrBuilder();
  }
  /**
   * Protobuf type {@code io.fragilebox.protocol.BenchmarkMessage}
   *
   * <pre>
   * Message to organize benchmark flow.
   *
   * Messages with type RUN are used to tell server to start sending benchmark
   * messages. It is possible to configure the benchmark by modifying "options" 
   * field. Identifier of the "run" message matches one of the "stop" message.
   *
   * Messages with type STOP are used by the server to tell the client that 
   * benchmark is finished (normally or unexpectedly). These messages contain
   * "result" field.
   *
   * Messages with type PAYLOAD_REQUEST are expected to contain non-zero payload.
   * Their identifiers will be used to match PAYLOAD_RESPONSE messages.
   *
   * Messages with type PAYLOAD_RESPONSE are expected to contain zero payload.
   * They should be used by client to tell the server that request has been 
   * processed. Its identifier should match one from the processed request.
   * </pre>
   */
  public static final class BenchmarkMessage extends
      com.google.protobuf.GeneratedMessage
      implements BenchmarkMessageOrBuilder {
    // Use BenchmarkMessage.newBuilder() to construct.
    private BenchmarkMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BenchmarkMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BenchmarkMessage defaultInstance;
    public static BenchmarkMessage getDefaultInstance() {
      return defaultInstance;
    }

    public BenchmarkMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BenchmarkMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              io.fragilebox.protocol.BoxProtocol.BenchmarkMessage.Type value = io.fragilebox.protocol.BoxProtocol.BenchmarkMessage.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 29: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                payload_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              payload_.add(input.readSFixed32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                payload_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                payload_.add(input.readSFixed32());
              }
              input.popLimit(limit);
              break;
            }
            case 34: {
              io.fragilebox.protocol.BoxProtocol.BenchmarkOptions.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = options_.toBuilder();
              }
              options_ = input.readMessage(io.fragilebox.protocol.BoxProtocol.BenchmarkOptions.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(options_);
                options_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 42: {
              io.fragilebox.protocol.BoxProtocol.BenchmarkResult.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = result_.toBuilder();
              }
              result_ = input.readMessage(io.fragilebox.protocol.BoxProtocol.BenchmarkResult.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(result_);
                result_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          payload_ = java.util.Collections.unmodifiableList(payload_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.fragilebox.protocol.BoxProtocol.internal_static_io_fragilebox_protocol_BenchmarkMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.fragilebox.protocol.BoxProtocol.internal_static_io_fragilebox_protocol_BenchmarkMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.fragilebox.protocol.BoxProtocol.BenchmarkMessage.class, io.fragilebox.protocol.BoxProtocol.BenchmarkMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<BenchmarkMessage> PARSER =
        new com.google.protobuf.AbstractParser<BenchmarkMessage>() {
      public BenchmarkMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BenchmarkMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BenchmarkMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code io.fragilebox.protocol.BenchmarkMessage.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>RUN = 0;</code>
       */
      RUN(0, 0),
      /**
       * <code>STOP = 1;</code>
       */
      STOP(1, 1),
      /**
       * <code>PAYLOAD_REQUEST = 2;</code>
       */
      PAYLOAD_REQUEST(2, 2),
      /**
       * <code>PAYLOAD_RESPONSE = 3;</code>
       */
      PAYLOAD_RESPONSE(3, 3),
      ;

      /**
       * <code>RUN = 0;</code>
       */
      public static final int RUN_VALUE = 0;
      /**
       * <code>STOP = 1;</code>
       */
      public static final int STOP_VALUE = 1;
      /**
       * <code>PAYLOAD_REQUEST = 2;</code>
       */
      public static final int PAYLOAD_REQUEST_VALUE = 2;
      /**
       * <code>PAYLOAD_RESPONSE = 3;</code>
       */
      public static final int PAYLOAD_RESPONSE_VALUE = 3;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 0: return RUN;
          case 1: return STOP;
          case 2: return PAYLOAD_REQUEST;
          case 3: return PAYLOAD_RESPONSE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return io.fragilebox.protocol.BoxProtocol.BenchmarkMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:io.fragilebox.protocol.BenchmarkMessage.Type)
    }

    private int bitField0_;
    // required .io.fragilebox.protocol.BenchmarkMessage.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private io.fragilebox.protocol.BoxProtocol.BenchmarkMessage.Type type_;
    /**
     * <code>required .io.fragilebox.protocol.BenchmarkMessage.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .io.fragilebox.protocol.BenchmarkMessage.Type type = 1;</code>
     */
    public io.fragilebox.protocol.BoxProtocol.BenchmarkMessage.Type getType() {
      return type_;
    }

    // required int32 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>required int32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    // repeated sfixed32 payload = 3;
    public static final int PAYLOAD_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> payload_;
    /**
     * <code>repeated sfixed32 payload = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getPayloadList() {
      return payload_;
    }
    /**
     * <code>repeated sfixed32 payload = 3;</code>
     */
    public int getPayloadCount() {
      return payload_.size();
    }
    /**
     * <code>repeated sfixed32 payload = 3;</code>
     */
    public int getPayload(int index) {
      return payload_.get(index);
    }

    // optional .io.fragilebox.protocol.BenchmarkOptions options = 4;
    public static final int OPTIONS_FIELD_NUMBER = 4;
    private io.fragilebox.protocol.BoxProtocol.BenchmarkOptions options_;
    /**
     * <code>optional .io.fragilebox.protocol.BenchmarkOptions options = 4;</code>
     */
    public boolean hasOptions() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .io.fragilebox.protocol.BenchmarkOptions options = 4;</code>
     */
    public io.fragilebox.protocol.BoxProtocol.BenchmarkOptions getOptions() {
      return options_;
    }
    /**
     * <code>optional .io.fragilebox.protocol.BenchmarkOptions options = 4;</code>
     */
    public io.fragilebox.protocol.BoxProtocol.BenchmarkOptionsOrBuilder getOptionsOrBuilder() {
      return options_;
    }

    // optional .io.fragilebox.protocol.BenchmarkResult result = 5;
    public static final int RESULT_FIELD_NUMBER = 5;
    private io.fragilebox.protocol.BoxProtocol.BenchmarkResult result_;
    /**
     * <code>optional .io.fragilebox.protocol.BenchmarkResult result = 5;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .io.fragilebox.protocol.BenchmarkResult result = 5;</code>
     */
    public io.fragilebox.protocol.BoxProtocol.BenchmarkResult getResult() {
      return result_;
    }
    /**
     * <code>optional .io.fragilebox.protocol.BenchmarkResult result = 5;</code>
     */
    public io.fragilebox.protocol.BoxProtocol.BenchmarkResultOrBuilder getResultOrBuilder() {
      return result_;
    }

    private void initFields() {
      type_ = io.fragilebox.protocol.BoxProtocol.BenchmarkMessage.Type.RUN;
      id_ = 0;
      payload_ = java.util.Collections.emptyList();
      options_ = io.fragilebox.protocol.BoxProtocol.BenchmarkOptions.getDefaultInstance();
      result_ = io.fragilebox.protocol.BoxProtocol.BenchmarkResult.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      for (int i = 0; i < payload_.size(); i++) {
        output.writeSFixed32(3, payload_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(4, options_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(5, result_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      {
        int dataSize = 0;
        dataSize = 4 * getPayloadList().size();
        size += dataSize;
        size += 1 * getPayloadList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, options_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.fragilebox.protocol.BoxProtocol.BenchmarkMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.fragilebox.protocol.BoxProtocol.BenchmarkMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.fragilebox.protocol.BoxProtocol.BenchmarkMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.fragilebox.protocol.BoxProtocol.BenchmarkMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.fragilebox.protocol.BoxProtocol.BenchmarkMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.fragilebox.protocol.BoxProtocol.BenchmarkMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.fragilebox.protocol.BoxProtocol.BenchmarkMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.fragilebox.protocol.BoxProtocol.BenchmarkMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.fragilebox.protocol.BoxProtocol.BenchmarkMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.fragilebox.protocol.BoxProtocol.BenchmarkMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.fragilebox.protocol.BoxProtocol.BenchmarkMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.fragilebox.protocol.BenchmarkMessage}
     *
     * <pre>
     * Message to organize benchmark flow.
     *
     * Messages with type RUN are used to tell server to start sending benchmark
     * messages. It is possible to configure the benchmark by modifying "options" 
     * field. Identifier of the "run" message matches one of the "stop" message.
     *
     * Messages with type STOP are used by the server to tell the client that 
     * benchmark is finished (normally or unexpectedly). These messages contain
     * "result" field.
     *
     * Messages with type PAYLOAD_REQUEST are expected to contain non-zero payload.
     * Their identifiers will be used to match PAYLOAD_RESPONSE messages.
     *
     * Messages with type PAYLOAD_RESPONSE are expected to contain zero payload.
     * They should be used by client to tell the server that request has been 
     * processed. Its identifier should match one from the processed request.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements io.fragilebox.protocol.BoxProtocol.BenchmarkMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.fragilebox.protocol.BoxProtocol.internal_static_io_fragilebox_protocol_BenchmarkMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.fragilebox.protocol.BoxProtocol.internal_static_io_fragilebox_protocol_BenchmarkMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.fragilebox.protocol.BoxProtocol.BenchmarkMessage.class, io.fragilebox.protocol.BoxProtocol.BenchmarkMessage.Builder.class);
      }

      // Construct using io.fragilebox.protocol.BoxProtocol.BenchmarkMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getOptionsFieldBuilder();
          getResultFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = io.fragilebox.protocol.BoxProtocol.BenchmarkMessage.Type.RUN;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        payload_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        if (optionsBuilder_ == null) {
          options_ = io.fragilebox.protocol.BoxProtocol.BenchmarkOptions.getDefaultInstance();
        } else {
          optionsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (resultBuilder_ == null) {
          result_ = io.fragilebox.protocol.BoxProtocol.BenchmarkResult.getDefaultInstance();
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.fragilebox.protocol.BoxProtocol.internal_static_io_fragilebox_protocol_BenchmarkMessage_descriptor;
      }

      public io.fragilebox.protocol.BoxProtocol.BenchmarkMessage getDefaultInstanceForType() {
        return io.fragilebox.protocol.BoxProtocol.BenchmarkMessage.getDefaultInstance();
      }

      public io.fragilebox.protocol.BoxProtocol.BenchmarkMessage build() {
        io.fragilebox.protocol.BoxProtocol.BenchmarkMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.fragilebox.protocol.BoxProtocol.BenchmarkMessage buildPartial() {
        io.fragilebox.protocol.BoxProtocol.BenchmarkMessage result = new io.fragilebox.protocol.BoxProtocol.BenchmarkMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          payload_ = java.util.Collections.unmodifiableList(payload_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.payload_ = payload_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        if (optionsBuilder_ == null) {
          result.options_ = options_;
        } else {
          result.options_ = optionsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        if (resultBuilder_ == null) {
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.fragilebox.protocol.BoxProtocol.BenchmarkMessage) {
          return mergeFrom((io.fragilebox.protocol.BoxProtocol.BenchmarkMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.fragilebox.protocol.BoxProtocol.BenchmarkMessage other) {
        if (other == io.fragilebox.protocol.BoxProtocol.BenchmarkMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (!other.payload_.isEmpty()) {
          if (payload_.isEmpty()) {
            payload_ = other.payload_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePayloadIsMutable();
            payload_.addAll(other.payload_);
          }
          onChanged();
        }
        if (other.hasOptions()) {
          mergeOptions(other.getOptions());
        }
        if (other.hasResult()) {
          mergeResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.fragilebox.protocol.BoxProtocol.BenchmarkMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.fragilebox.protocol.BoxProtocol.BenchmarkMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .io.fragilebox.protocol.BenchmarkMessage.Type type = 1;
      private io.fragilebox.protocol.BoxProtocol.BenchmarkMessage.Type type_ = io.fragilebox.protocol.BoxProtocol.BenchmarkMessage.Type.RUN;
      /**
       * <code>required .io.fragilebox.protocol.BenchmarkMessage.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .io.fragilebox.protocol.BenchmarkMessage.Type type = 1;</code>
       */
      public io.fragilebox.protocol.BoxProtocol.BenchmarkMessage.Type getType() {
        return type_;
      }
      /**
       * <code>required .io.fragilebox.protocol.BenchmarkMessage.Type type = 1;</code>
       */
      public Builder setType(io.fragilebox.protocol.BoxProtocol.BenchmarkMessage.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .io.fragilebox.protocol.BenchmarkMessage.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = io.fragilebox.protocol.BoxProtocol.BenchmarkMessage.Type.RUN;
        onChanged();
        return this;
      }

      // required int32 id = 2;
      private int id_ ;
      /**
       * <code>required int32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      // repeated sfixed32 payload = 3;
      private java.util.List<java.lang.Integer> payload_ = java.util.Collections.emptyList();
      private void ensurePayloadIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          payload_ = new java.util.ArrayList<java.lang.Integer>(payload_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated sfixed32 payload = 3;</code>
       */
      public java.util.List<java.lang.Integer>
          getPayloadList() {
        return java.util.Collections.unmodifiableList(payload_);
      }
      /**
       * <code>repeated sfixed32 payload = 3;</code>
       */
      public int getPayloadCount() {
        return payload_.size();
      }
      /**
       * <code>repeated sfixed32 payload = 3;</code>
       */
      public int getPayload(int index) {
        return payload_.get(index);
      }
      /**
       * <code>repeated sfixed32 payload = 3;</code>
       */
      public Builder setPayload(
          int index, int value) {
        ensurePayloadIsMutable();
        payload_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sfixed32 payload = 3;</code>
       */
      public Builder addPayload(int value) {
        ensurePayloadIsMutable();
        payload_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sfixed32 payload = 3;</code>
       */
      public Builder addAllPayload(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensurePayloadIsMutable();
        super.addAll(values, payload_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sfixed32 payload = 3;</code>
       */
      public Builder clearPayload() {
        payload_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // optional .io.fragilebox.protocol.BenchmarkOptions options = 4;
      private io.fragilebox.protocol.BoxProtocol.BenchmarkOptions options_ = io.fragilebox.protocol.BoxProtocol.BenchmarkOptions.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          io.fragilebox.protocol.BoxProtocol.BenchmarkOptions, io.fragilebox.protocol.BoxProtocol.BenchmarkOptions.Builder, io.fragilebox.protocol.BoxProtocol.BenchmarkOptionsOrBuilder> optionsBuilder_;
      /**
       * <code>optional .io.fragilebox.protocol.BenchmarkOptions options = 4;</code>
       */
      public boolean hasOptions() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .io.fragilebox.protocol.BenchmarkOptions options = 4;</code>
       */
      public io.fragilebox.protocol.BoxProtocol.BenchmarkOptions getOptions() {
        if (optionsBuilder_ == null) {
          return options_;
        } else {
          return optionsBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .io.fragilebox.protocol.BenchmarkOptions options = 4;</code>
       */
      public Builder setOptions(io.fragilebox.protocol.BoxProtocol.BenchmarkOptions value) {
        if (optionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          options_ = value;
          onChanged();
        } else {
          optionsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .io.fragilebox.protocol.BenchmarkOptions options = 4;</code>
       */
      public Builder setOptions(
          io.fragilebox.protocol.BoxProtocol.BenchmarkOptions.Builder builderForValue) {
        if (optionsBuilder_ == null) {
          options_ = builderForValue.build();
          onChanged();
        } else {
          optionsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .io.fragilebox.protocol.BenchmarkOptions options = 4;</code>
       */
      public Builder mergeOptions(io.fragilebox.protocol.BoxProtocol.BenchmarkOptions value) {
        if (optionsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              options_ != io.fragilebox.protocol.BoxProtocol.BenchmarkOptions.getDefaultInstance()) {
            options_ =
              io.fragilebox.protocol.BoxProtocol.BenchmarkOptions.newBuilder(options_).mergeFrom(value).buildPartial();
          } else {
            options_ = value;
          }
          onChanged();
        } else {
          optionsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .io.fragilebox.protocol.BenchmarkOptions options = 4;</code>
       */
      public Builder clearOptions() {
        if (optionsBuilder_ == null) {
          options_ = io.fragilebox.protocol.BoxProtocol.BenchmarkOptions.getDefaultInstance();
          onChanged();
        } else {
          optionsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .io.fragilebox.protocol.BenchmarkOptions options = 4;</code>
       */
      public io.fragilebox.protocol.BoxProtocol.BenchmarkOptions.Builder getOptionsBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getOptionsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .io.fragilebox.protocol.BenchmarkOptions options = 4;</code>
       */
      public io.fragilebox.protocol.BoxProtocol.BenchmarkOptionsOrBuilder getOptionsOrBuilder() {
        if (optionsBuilder_ != null) {
          return optionsBuilder_.getMessageOrBuilder();
        } else {
          return options_;
        }
      }
      /**
       * <code>optional .io.fragilebox.protocol.BenchmarkOptions options = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          io.fragilebox.protocol.BoxProtocol.BenchmarkOptions, io.fragilebox.protocol.BoxProtocol.BenchmarkOptions.Builder, io.fragilebox.protocol.BoxProtocol.BenchmarkOptionsOrBuilder> 
          getOptionsFieldBuilder() {
        if (optionsBuilder_ == null) {
          optionsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              io.fragilebox.protocol.BoxProtocol.BenchmarkOptions, io.fragilebox.protocol.BoxProtocol.BenchmarkOptions.Builder, io.fragilebox.protocol.BoxProtocol.BenchmarkOptionsOrBuilder>(
                  options_,
                  getParentForChildren(),
                  isClean());
          options_ = null;
        }
        return optionsBuilder_;
      }

      // optional .io.fragilebox.protocol.BenchmarkResult result = 5;
      private io.fragilebox.protocol.BoxProtocol.BenchmarkResult result_ = io.fragilebox.protocol.BoxProtocol.BenchmarkResult.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          io.fragilebox.protocol.BoxProtocol.BenchmarkResult, io.fragilebox.protocol.BoxProtocol.BenchmarkResult.Builder, io.fragilebox.protocol.BoxProtocol.BenchmarkResultOrBuilder> resultBuilder_;
      /**
       * <code>optional .io.fragilebox.protocol.BenchmarkResult result = 5;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .io.fragilebox.protocol.BenchmarkResult result = 5;</code>
       */
      public io.fragilebox.protocol.BoxProtocol.BenchmarkResult getResult() {
        if (resultBuilder_ == null) {
          return result_;
        } else {
          return resultBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .io.fragilebox.protocol.BenchmarkResult result = 5;</code>
       */
      public Builder setResult(io.fragilebox.protocol.BoxProtocol.BenchmarkResult value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          result_ = value;
          onChanged();
        } else {
          resultBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .io.fragilebox.protocol.BenchmarkResult result = 5;</code>
       */
      public Builder setResult(
          io.fragilebox.protocol.BoxProtocol.BenchmarkResult.Builder builderForValue) {
        if (resultBuilder_ == null) {
          result_ = builderForValue.build();
          onChanged();
        } else {
          resultBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .io.fragilebox.protocol.BenchmarkResult result = 5;</code>
       */
      public Builder mergeResult(io.fragilebox.protocol.BoxProtocol.BenchmarkResult value) {
        if (resultBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              result_ != io.fragilebox.protocol.BoxProtocol.BenchmarkResult.getDefaultInstance()) {
            result_ =
              io.fragilebox.protocol.BoxProtocol.BenchmarkResult.newBuilder(result_).mergeFrom(value).buildPartial();
          } else {
            result_ = value;
          }
          onChanged();
        } else {
          resultBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .io.fragilebox.protocol.BenchmarkResult result = 5;</code>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = io.fragilebox.protocol.BoxProtocol.BenchmarkResult.getDefaultInstance();
          onChanged();
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .io.fragilebox.protocol.BenchmarkResult result = 5;</code>
       */
      public io.fragilebox.protocol.BoxProtocol.BenchmarkResult.Builder getResultBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getResultFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .io.fragilebox.protocol.BenchmarkResult result = 5;</code>
       */
      public io.fragilebox.protocol.BoxProtocol.BenchmarkResultOrBuilder getResultOrBuilder() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilder();
        } else {
          return result_;
        }
      }
      /**
       * <code>optional .io.fragilebox.protocol.BenchmarkResult result = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          io.fragilebox.protocol.BoxProtocol.BenchmarkResult, io.fragilebox.protocol.BoxProtocol.BenchmarkResult.Builder, io.fragilebox.protocol.BoxProtocol.BenchmarkResultOrBuilder> 
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              io.fragilebox.protocol.BoxProtocol.BenchmarkResult, io.fragilebox.protocol.BoxProtocol.BenchmarkResult.Builder, io.fragilebox.protocol.BoxProtocol.BenchmarkResultOrBuilder>(
                  result_,
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:io.fragilebox.protocol.BenchmarkMessage)
    }

    static {
      defaultInstance = new BenchmarkMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:io.fragilebox.protocol.BenchmarkMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_io_fragilebox_protocol_BenchmarkResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_fragilebox_protocol_BenchmarkResult_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_io_fragilebox_protocol_BenchmarkOptions_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_fragilebox_protocol_BenchmarkOptions_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_io_fragilebox_protocol_BenchmarkMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_fragilebox_protocol_BenchmarkMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(io/fragilebox/protocol/BoxProtocol.pro" +
      "to\022\026io.fragilebox.protocol\"A\n\017BenchmarkR" +
      "esult\022\023\n\013messageTime\030\001 \001(\003\022\031\n\021processedM" +
      "essages\030\002 \001(\005\">\n\020BenchmarkOptions\022\025\n\rben" +
      "chmarkSize\030\003 \001(\005\022\023\n\013payloadSize\030\004 \001(\005\"\246\002" +
      "\n\020BenchmarkMessage\022;\n\004type\030\001 \002(\0162-.io.fr" +
      "agilebox.protocol.BenchmarkMessage.Type\022" +
      "\n\n\002id\030\002 \002(\005\022\017\n\007payload\030\003 \003(\017\0229\n\007options\030" +
      "\004 \001(\0132(.io.fragilebox.protocol.Benchmark" +
      "Options\0227\n\006result\030\005 \001(\0132\'.io.fragilebox.",
      "protocol.BenchmarkResult\"D\n\004Type\022\007\n\003RUN\020" +
      "\000\022\010\n\004STOP\020\001\022\023\n\017PAYLOAD_REQUEST\020\002\022\024\n\020PAYL" +
      "OAD_RESPONSE\020\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_io_fragilebox_protocol_BenchmarkResult_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_io_fragilebox_protocol_BenchmarkResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_io_fragilebox_protocol_BenchmarkResult_descriptor,
              new java.lang.String[] { "MessageTime", "ProcessedMessages", });
          internal_static_io_fragilebox_protocol_BenchmarkOptions_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_io_fragilebox_protocol_BenchmarkOptions_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_io_fragilebox_protocol_BenchmarkOptions_descriptor,
              new java.lang.String[] { "BenchmarkSize", "PayloadSize", });
          internal_static_io_fragilebox_protocol_BenchmarkMessage_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_io_fragilebox_protocol_BenchmarkMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_io_fragilebox_protocol_BenchmarkMessage_descriptor,
              new java.lang.String[] { "Type", "Id", "Payload", "Options", "Result", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
